### PR TITLE
Bundle improvement

### PR DESCRIPTION
**Pull request by dariuskasiulevicius**
- compser cannot found latest tag, trying up version
- fixed typo in composer.json
- catch logger error if service down
- do not try to reinitialize FluentLogger if it failed once
- disable logging if host is not provided
- Removed folder 'bundle' from namespace
- Removed IDE specific files
- Renamed class names to correct Symfony pattern

### CODE REVIEW

**Comment by Elexy** [comment]
Thanks, I will review asap

**Comment by dariuskasiulevicius** [comment]
More changes

**Comment by Elexy** [comment]
wow, thanks. Away from office, will try to check later.

**Comment by the-mandarine** [comment]
Hi, 
The last two commits (e09cf08 and a1aa967) seem to actually break stuff.
In my point of view, the tag does not always need to contain the machine hostname.
I believe that respecting what the user configured as tag might be more generally useful.
If there is a way of avoiding the hostname appearing in tag, don't consider this message :smile: 
Best regards

**Comment by Elexy** [comment]
Guys, I'm not using this bundle anymore, anyone want to take ownership?
I have too many side projects to maintain this.

**Pull request merged**
